# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Vercel
      run: |
        echo "${{ secrets.VERCEL_TOKEN }}" | vercel login --token

    - name: Build and Deploy
      run: |
        docker build -t your-app-name ./app
        vercel --prod
